const PRODUCTS = [
  {
    id: "chain-1",
    name: "Cuban Chain",
    category: "chains",
    price: 2999,
    image: "chains/chain (1).jpg",
  },
  {
    id: "chain-2",
    name: "Reaver Chain",
    category: "chains",
    price: 2799,
    image: "chains/chain (2).jpg",
  },
  {
    id: "chain-3",
    name: "Foxtail Chain",
    category: "chains",
    price: 2699,
    image: "chains/chain (3).jpg",
  },
  {
    id: "chain-4",
    name: "Rope Chain",
    category: "chains",
    price: 2899,
    image: "chains/chain (4).jpg",
  },
  {
    id: "bracelet-1",
    name: "Cuban Bracelet",
    category: "bracelets",
    price: 2499,
    image: "bracelets/bracelet (1).jpg",
  },
  {
    id: "bracelet-2",
    name: "Halo Bracelet",
    category: "bracelets",
    price: 2299,
    image: "bracelets/bracelet (2).jpg",
  },
  {
    id: "bracelet-3",
    name: "Star Bracelet",
    category: "bracelets",
    price: 2199,
    image: "bracelets/bracelet (3).jpg",
  },
  {
    id: "bracelet-4",
    name: "Van Cleaf Bracelet",
    category: "bracelets",
    price: 2399,
    image: "bracelets/bracelet (4).jpg",
  },
  {
    id: "earring-1",
    name: "Kaze Leaf Earring",
    category: "earrings",
    price: 899,
    image: "earrings/earring (1).jpg",
  },
  {
    id: "earring-2",
    name: "Raijin Bolt Earring",
    category: "earrings",
    price: 799,
    image: "earrings/earring (2).jpg",
  },
  {
    id: "earring-3",
    name: "Stellar Drop Earring",
    category: "earrings",
    price: 999,
    image: "earrings/earring (3).jpg",
  },
  {
    id: "earring-4",
    name: "Kai Star",
    category: "earrings",
    price: 849,
    image: "earrings/earring (4).jpg",
  },
  {
    id: "earring-5",
    name: "Shuriken Eye Earring",
    category: "earrings",
    price: 949,
    image: "earrings/earring (5).jpg",
  },
  {
    id: "ring-1",
    name: "Batman Ring",
    category: "rings",
    price: 1299,
    image: "rings/ring (1).jpg",
  },
  {
    id: "ring-2",
    name: "Cross Ring",
    category: "rings",
    price: 1399,
    image: "rings/ring (2).jpg",
  },
  {
    id: "ring-3",
    name: "Sword Ring",
    category: "rings",
    price: 1499,
    image: "rings/ring (3).jpg",
  },
  {
    id: "ring-4",
    name: "Ryzen Ring",
    category: "rings",
    price: 1599,
    image: "rings/ring (4).jpg",
  },
  {
    id: "ring-5",
    name: "Valcrest Ring",
    category: "rings",
    price: 1699,
    image: "rings/ring (5).jpg",
  },
  {
    id: "bandana-1",
    name: "Samuraii Bandana I",
    category: "bandanas",
    price: 599,
    image: "bandanas/bandana1.jpg",
  },
  {
    id: "bandana-2",
    name: "Samuraii Bandana II",
    category: "bandanas",
    price: 649,
    image: "bandanas/bandana2.jpg",
  },
  {
    id: "tote-1",
    name: "Samuraii Tote Bag I",
    category: "tote",
    price: 1199,
    image: "tote/tote1.jpg",
  },
  {
    id: "tote-2",
    name: "Samuraii Tote Bag II",
    category: "tote",
    price: 1299,
    image: "tote/tote2.jpg",
  },
];

const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "chains", label: "Chains" },
  { id: "bracelets", label: "Bracelets" },
  { id: "earrings", label: "Earrings" },
  { id: "rings", label: "Rings" },
  { id: "bandanas", label: "Bandanas" },
  { id: "tote", label: "Tote" },
];

/** Home page category tiles — uses plural .jpg in folder when present */
const SHOP_CATEGORIES = [
  { id: "chains", label: "Chains", image: "chains/chain (1).jpg" },
  { id: "bracelets", label: "Bracelets", image: "bracelets/bracelet (1).jpg" },
  { id: "earrings", label: "Earrings", image: "earrings/earring (2).jpg" },
  { id: "rings", label: "Rings", image: "rings/ring (1).jpg" },
  { id: "bandanas", label: "Bandanas", image: "bandanas/bandana1.jpg" },
  { id: "tote", label: "Tote", image: "tote/tote1.jpg" },
];
